### ISSUE TITLE
Implement Automatic Type Conversions for Rule File Terms

### ISSUE THREAD

**Issue by monsterkrampe** [knowsys/nemo#244]
There are some obvious type conversions that currently produce type errors.
For example, if you use the term `2.0` in a `Float64` column in a rule file it gives a type error, since `2.0` is parsed a `Decimal` and not `Double`. We currently only support proper `Double`s for `Float64` columns.
Before implementing this, I think there is some discussion needed on which conversions we want to allow.
Sometimes too many implicit casts may make it harder for users to spot errors.
For example it may be worthwhile to force users to put quotes around values that go into `String` columns, e.g. to write `"2"` instead of just `2`.

In any case, error messages should be improved to give suggestions like: `did you mean to write 2.0E0`?

**Comment by mmarx** [comment]
My understanding would be that during parsing, we treat a numeric literal value like `2` or even `2.0` (but, notably, not `2.7` or `2.7182818284590`) as an element of some universal `Number` type that has no defined storage type, but is implicitly coercible to `Integer`, `UnsignedInteger`, `Float`, and `Double` (numeric literal values like `2.7` would only be implicitly coercible to `Float` and to `Double`, but, e.g., not to `Integer`). Then, during type checking, we would assign a “proper” numeric type to those positions (or promote them to `any`) based on the usage (we might need some default rule to resolve any ambiguities here, probably `Integer` makes the most sense as a fallback type).

**Comment by mkroetzsch** [comment]
I agree with Max's proposal. The "union" type for "decimal notation number" is interesting for type inference, since it cannot be represented as an interval (float and decimal being incomparable), but this seems unavoidable (@matzemathics). I think allowing 2 to represent a float is ok (I don't see any issue with this, and it might be handy for people who process JSON where all numbers are float and you might also have a plain 2, I suppose). 

Strings in rules files should always have quotes around them, so 2 should never be a valid string.

This discussion is only about rules files. The way in which one would read, e.g., strings from CSV, can be different.

**Comment by monsterkrampe** [comment]
This has been resolved by allowing implicit casts from Numeric Integer Literals and Numeric Decimal Literals to `Float64`.
The corresponding RDF Literals are not casted though.
We don't do any other automatic conversions for now.
Error messages have not been changed.
