### ISSUE TITLE
Large integer/decimal values are not accepted in parsing

### ISSUE THREAD

**Issue by larry-gonzalez** [knowsys/nemo#321]
(Seen on commit 4805f19)

When loading RDF data from Wikidata we encounter some values that fail to convert to type any

The following is a log entry of such case
```
INFO  nemo::io::formats::rdf_triples] Ignoring malformed triple: Failed to convert value "+9950000000000000000"^^<http://www.w3.org/2001/XMLSchema#decimal> to type any.
```

Attached you can find some RDF triples, a rule file that would load the data and extract the value in the object position, and the log produced when running nemo

[triples.nt.gz](https://github.com/knowsys/nemo/files/12094760/triples.nt.gz)
[rules.rls.gz](https://github.com/knowsys/nemo/files/12094764/rules.rls.gz)
[log.log.gz](https://github.com/knowsys/nemo/files/12094782/log.log.gz)

**Comment by mmarx** [comment]
The underlying problem is that we currently only support integers that fit into `i64`, and only decimals where the whole part fits into `i64` and the fractional part fits into `u64`. There are some provisions for handling such cases in [XSD](https://www.w3.org/TR/xmlschema11-2/#partial-implementation), and while we are not required to handle input as above, I believe that at the very least we need to clearly signal this, instead of just ignoring the triple as invalid, and we might also want to support storing such values (likely as `any` internally) – which leads to the question if we want to support, e.g., arithmetics on it.

**Comment by monsterkrampe** [comment]
Proposed solution:
When reading values into any, we fall back to just storing the value as a generic datatype value literal (which excludes it from potential arithmetic operations and comparisons that we would plan to support otherwise).
When reading into e.g. integer, we still ignore the value as we do now (logging that the value is excluded but not throwing an error).
