### ISSUE TITLE
Document concept of `negative_filters`

### ISSUE THREAD

**Issue by matzemathics** [knowsys/nemo#357]
While working on fixing the normalization code (cf #355) I was wondering what was the intention behind `ChaseRule.negative_filters`. The documentation seems unhelpful here. Additionally, they are, as far as I can see at least, currently unused (only over set to the empty vector, and never updated). My proposal would be to remove them.

@aannleax am I missing something here?

Edit: after some more reading, it seems these filters were probably supposed to be applied negated? However then methods like `all_filters` do not really make sense, since it just lumps positive and negative filters together.

**Comment by matzemathics** [comment]
after thinking some more about this, i really found one usage of negative filters: equality constraints in negative atoms are generated as negative filters.

**Comment by mmarx** [comment]
With #358 we get rid of negative filters, don't we?

**Comment by matzemathics** [comment]
> With #358 we get rid of negative filters, don't we?

No not really, I just removed it from the constructor, because they are only generated by normalisation. I _think _, they are still needed, but at least they can be simplified, since they are always equality constraints.

**Comment by aannleax** [comment]
"after thinking some more about this, i really found one usage of negative filters: equality constraints in negative atoms are generated as negative filters."
Yes this is the main use case right now.

"No not really, I just removed it from the constructor, because they are only generated by normalisation. I _think _, they are still needed, but at least they can be simplified, since they are always equality constraints."
This is the only use case right now. But we do support unsafe variables in negated literals
```
R(?x) :- P(?x), N(?x, ?y) . 
```
One could support additional constraints on `?y`. I think the planning code would support this even right now (as it just uses the same code as for the filters as in the positive case) but we currently don't allow it.

**Comment by matzemathics** [comment]
@aannleax this still leaves me wondering, exactly when a constraint should appear in the positive versus negative set, because if a variable appears in both positive and negative literals it would be in a positive constraint, right? Does negative constraint in this case stand for a constraint on an _unsafe_ variable?

**Comment by aannleax** [comment]
@matzemathics Constraints on unsafe variables is a good approximation. More concretely:

The evaluation of the rule body is a two step process: The positive part and negative part that subtracts values generated in the first step. The positive filters are the ones that are applied in the first step and the negative the ones that are applied in the second step. I'm not sure if there is a use case for constraining positive variables in the negative part, so this just leaves constraints on unsafe variables (user provided or generated through normalization).
